### ISSUE TITLE
Linode is already active 

### ISSUE THREAD

**Issue by HeathNaylor** [displague/vagrant-linode#54] opened 2015-11-12 20:37 UTC
I have 2 folders within my project, I am trying to use Vagrant Linode for multiple environments (staging and production). When I `vagrant ssh` from the `vagrant-production` folder I get access to the `vagrant- staging` server.

```
$ vagrant up --provider=linode
Bringing machine 'default' up with 'linode' provider...
==> default: Linode is already active
```

**Comment by displague** [comment] 2015-11-12 20:56
Did you copy the folder after bringing up the Linode in the first environment?

The linodeid is kept within a .vagrant directory in the directory where the Vagrant file is stored.

Have a look at https://gist.github.com/displague/1605285f0bf8fe4a251e for an example of running multiple vagrant instances from a single folder / Vagrantfile.

**Comment by displague** [comment] 2016-02-05 22:26
@HeathNaylor were you able to get your multiple host environment working?

**Comment by displague** [comment] 2017-11-19 20:18
I'm closing this do to staleness and changes to the plugin since this issue was reported.  Please reopen this if the problem is still occurring.

**Closed by displague** 2017-11-19 20:18 UTC
