### ISSUE TITLE
Error "Size is required but was not passed in"

### ISSUE THREAD

**Issue by nodje** [displague/vagrant-linode#72] opened 2017-05-03 13:30 UTC
Hi, I get this error:
```
.vagrant.d/gems/2.2.5/gems/linodeapi-1.0.1/lib/linodeapi/raw.rb:87:in `parse': API Error on linode.disk.create: [{"ERRORMESSAGE"=>"Size is required but was not passed in", "ERRORCODE"=>6}] (RuntimeError)
```
with this specific config:
```
config.vm.provider :linode do |provider, override|
    override.ssh.private_key_path = "~/.ssh/id_ed25519"
    #override.ssh.username = "root"
    override.vm.box = "linode/ubuntu1404"
    provider.ssh_key_name = "root"
    provider.setup = false
    provider.api_key = "AvalidKey"
    provider.distribution = "Ubuntu 14.04 LTS"
    provider.datacenter = "frankfurt"
    provider.plan = "Linode 1024"
    provider.label = "Ansible_test"
  end
```
if i remove the `provide.setup = false` line, it just works.

Basically all I wanted to do is make sure my pub key gets uploaded to the default `root` user of any Linode box and be able to connect to it. From the doc I gathered I had to set `provider.setup = false` so as not to create anything for an existing user.

Then the vagrant process fails (even though I can manually ssh to the new Linode box):
```
.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/create.rb:246:in `block in call': not ready (RuntimeError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /Users/jean/.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/create.rb:244:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jean/.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/connect_linode.rb:31:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/jean/.vagrant.d/gems/2.2.5/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/message_not_created.rb:11:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/environment.rb:567:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by nodje** [comment] 2017-05-05 11:29
I believe using ed25519 SSH keys is the problem, at least for not being able to connect when I remove the `provide.setup = false` line.
It works with an rsa key.

**Comment by displague** [comment] 2017-06-15 04:18
Is this perhaps a dupe of https://github.com/displague/vagrant-linode/issues/72 or is your scenario always repeatable with an specific ssh key path?

**Comment by displague** [comment] 2017-12-27 17:27
I'm also aware of an intermittent API bug that can sometime produce: `Size is required but was not passed in`, which would be completely unrelated to your Vagrantfile config.

Please reopen this if the issue persists in newer versions of the plugin.

**Closed by displague** 2017-12-27 17:27 UTC

**Comment by mywkaa** [comment] 2018-07-31 08:45
Hello , after updating vagrant from v2.0.0 to v2.1.2 i have started facing with the same issue :

`[{"ERRORMESSAGE"=>"Size is required but was not passed in", "ERRORCODE"=>6}]`

`/var/jenkins_home/.vagrant.d/gems/2.4.4/gems/linodeapi-2.0.1/lib/linodeapi/helpers.rb:23:in `parse': API Error encountered (LinodeAPI::APIError)
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/linodeapi-2.0.1/lib/linodeapi/helpers.rb:10:in `error_check'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/linodeapi-2.0.1/lib/linodeapi/raw.rb:84:in `call'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/linodeapi-2.0.1/lib/linodeapi/retryable.rb:20:in `call_with_retries'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/linodeapi-2.0.1/lib/linodeapi/retryable.rb:16:in `call'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/linodeapi-2.0.1/lib/linodeapi/raw.rb:78:in `block in make_call'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/linodeapi-2.0.1/lib/linodeapi/raw.rb:79:in `make_call'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/linodeapi-2.0.1/lib/linodeapi/raw.rb:60:in `method_missing'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/vagrant-linode-0.4.0/lib/vagrant-linode/client_wrapper.rb:12:in `method_missing'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/vagrant-linode-0.4.0/lib/vagrant-linode/actions/create.rb:173:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/vagrant-linode-0.4.0/lib/vagrant-linode/actions/connect_linode.rb:32:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	from /var/jenkins_home/.vagrant.d/gems/2.4.4/gems/vagrant-linode-0.4.0/lib/vagrant-linode/actions/message_not_created.rb:11:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:239:in `action_raw'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:208:in `block in action'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:598:in `lock'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:194:in `call'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/machine.rb:194:in `action'
	from /opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'`

**Comment by terodev** [comment] 2018-09-02 12:16
I got this error too, but managed to get my machine up and running with the following config block:

config.vm.provider :linode do |provider, override|
    override.ssh.username = 'my-username'
    override.ssh.private_key_path = '~/.ssh/my-private-key'
    override.vm.box = 'linode/ubuntu1804'
    override.vm.box_url = "https://github.com/displague/vagrant-linode/raw/master/box/linode.box"
    override.vm.synced_folder '.', '/vagrant', type: "rsync"
    provider.token = 'my-api-token'
    provider.distribution = 'Ubuntu 18.04 LTS'
    provider.datacenter = 'frankfurt'
    **provider.plan = 'Linode 2GB'**
    provider.label = 'vagrant-ubuntu-lts'
  end
